/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nut_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(62036068cbdc4aba446e07d5f8993372)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nut/nut_source.h>
// pydoc.h is automatically generated in the build directory
#include <nut_source_pydoc.h>

void bind_nut_source(py::module& m)
{

    using nut_source    = gr::nut::nut_source;


    py::class_<nut_source, gr::block, gr::basic_block,
        std::shared_ptr<nut_source>>(m, "nut_source", D(nut_source))

        .def(py::init(&nut_source::make),
             py::arg("uri"),
             py::arg("audio_channels"),
             py::arg("audio_rate"),
             py::arg("emit_video"),
             py::arg("video_width"),
             py::arg("video_height"),
             py::arg("command") = "",
             D(nut_source, make))

        // start()/stop() are exposed so the contract validation (which runs
        // in start() and throws std::runtime_error on any stream/profile
        // mismatch) can be exercised directly, e.g. from the QA tests.
        .def(
            "start",
            [](nut_source& self) { return self.start(); },
            py::call_guard<py::gil_scoped_release>())
        .def(
            "stop",
            [](nut_source& self) { return self.stop(); },
            py::call_guard<py::gil_scoped_release>())

        ;




}








