/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nut_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(54e24d1822da65b339e031ca1ab17210)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nut/nut_sink.h>
// pydoc.h is automatically generated in the build directory
#include <nut_sink_pydoc.h>

void bind_nut_sink(py::module& m)
{

    using nut_sink    = gr::nut::nut_sink;


    py::class_<nut_sink, gr::block, gr::basic_block,
        std::shared_ptr<nut_sink>>(m, "nut_sink", D(nut_sink))

        .def(py::init(&nut_sink::make),
             py::arg("uri"),
             py::arg("audio_channels"),
             py::arg("audio_rate"),
             py::arg("video_streams"),
             py::arg("widths"),
             py::arg("heights"),
             py::arg("fps"),
             py::arg("command") = "",
             py::arg("flush_timeout") = 10.0,
             D(nut_sink, make))

        // Post-constructor failures never throw (GR cannot propagate
        // block-thread exceptions); they are logged at ERROR level and end
        // the flowgraph cleanly. last_error() is the programmatic signal:
        // non-empty after tb.run()/wait() means the block failed, "" means
        // a clean stop.
        .def("last_error", &nut_sink::last_error)

        .def(
            "start",
            [](nut_sink& self) { return self.start(); },
            py::call_guard<py::gil_scoped_release>())
        .def(
            "stop",
            [](nut_sink& self) { return self.stop(); },
            py::call_guard<py::gil_scoped_release>())

        ;




}
