/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nut_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(594d570dae5ec614ea5aa77f69f79516)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nut/nut_source.h>
// pydoc.h is automatically generated in the build directory
#include <nut_source_pydoc.h>

void bind_nut_source(py::module& m)
{

    using nut_source    = gr::nut::nut_source;


    py::class_<nut_source, gr::block, gr::basic_block,
        std::shared_ptr<nut_source>>(m, "nut_source", D(nut_source))

        .def(py::init(&nut_source::make),
             py::arg("uri"),
             py::arg("audio_channels"),
             py::arg("video_streams"),
             py::arg("command") = "",
             D(nut_source, make))

        // Format adopted from the NUT stream headers; 0 before the
        // flowgraph has started or if the instance lacks that stream.
        // video_width/video_height take the video stream index (default 0).
        .def("audio_rate", &nut_source::audio_rate)
        .def("video_width", &nut_source::video_width, py::arg("stream") = 0)
        .def("video_height", &nut_source::video_height, py::arg("stream") = 0)

        // Post-constructor failures never throw (GR cannot propagate
        // block-thread exceptions); they are logged at ERROR level and end
        // the flowgraph cleanly. last_error() is the programmatic signal:
        // non-empty after tb.run()/wait() means the block failed, "" means
        // clean EOF.
        .def("last_error", &nut_source::last_error)

        .def(
            "start",
            [](nut_source& self) { return self.start(); },
            py::call_guard<py::gil_scoped_release>())
        .def(
            "stop",
            [](nut_source& self) { return self.stop(); },
            py::call_guard<py::gil_scoped_release>())

        ;




}








